djangopinax/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^account/social/accounts/$", TemplateView.as_view(template_name="account/social.html"), name="account_social_accounts"),
    url(r"^account/social/", include("social_django.urls", namespace="social")),
    url(r'^mods/', include('mods.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mods/urls.py
from django.conf.urls import url
from django.conf.urls import include

from . import views

app_name = 'mods'
urlpatterns = [
    url(r'^$', views.listcategories, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.PublicationView.as_view(), name='publicationview'),
    #url(r'^(?P<pk>[0-9]+)/$', views.Publication.as_view(), name='publicationview'),
    url(r'^(?P<publication_id>[0-9]+)/file/(?P<pk>[0-9]+)/$', views.FileView.as_view(), name='viewfile'),
    # url(r'^(?P<publication_id>[0-9]+)/file/(?P<file_id>[0-9]+)/download/$', views.GoToDownload, name='GoToDownload'),
    url(r'^file/(?P<file_id>[0-9]+)/$', views.downloader, name='goToDownload'),
    url(r'^(?P<publication_id>[0-9]+)/upload/$', views.upload, name='upload'),
    url(r'^(?P<publication_id>[0-9]+)/report/$', views.ReportView.as_view(), name='report'),

    url(r'^user/(?P<author>.+)/', views.UserPublications.as_view(), name='userpublications'),
    url(r'^modpublications/', views.ModPublications.as_view(), name='modpublications'),

    # zarzadzanie publikacjami:
    url(r'^(?P<pk>[0-9]+)/edit/$', views.PublicationEdit.as_view(), name='publicationedit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.PublicationDelete.as_view(), name='publicationdelete'),
    #url(r'^newpublication/', views.newPublication, name='newpublication'),
    url(r'^categoryview/(?P<category_slug>.+)/newpublication/', views.PublicationCreate.as_view(), name='newpublicationwithcategory'),
    url(r'^newpublication/', views.PublicationCreate.as_view(), name='newpublication'),

    url(r'^categoryview/(?P<category_slug>.+)/', views.categoryview, name='categoryview'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^user/(?P<author>.+)/', views.UserPublications.as_view(), name='userpublications'),
]

djangopinax/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <li class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </li>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

djangopinax/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 &lt;your company here&gt;" %}

djangopinax/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}Welcome to<br>pinax-project-account{% endblocktrans %}</h1>

            <p>You can <a href="{% url 'mods:index' %}" class="btn btn-default">PRZEJDZ SOBIE DO STRONY GLOWNEJ</a>

            <p>
                {% blocktrans %}
                In addition to what is provided by the "zero" project, this project
                provides thorough integration with django-user-accounts, adding
                comprehensive account management functionality. It is a foundation
                suitable for most sites that have user accounts.
                {% endblocktrans %}
            </p>
            {% if not user.is_authenticated %}
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p>{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to try out the site.{% endblocktrans %}</p>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="container">
            <h2 class="text-center">{% blocktrans %}What is Pinax?{% endblocktrans %}</h2>
            <p class="lead">
                {% blocktrans %}
                <b>Pinax</b> is an open-source platform based on Django and
                intended to provide a starting point for websites. It takes
                care of the things that many sites have in common, so you can
                focus on what makes your site different.
                {% endblocktrans %}
            </p>
            <div class="feature-columns">
                <div>
                    <i class="fa fa-cubes fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Starter projects</b> provide project layout,
                    scaffolding, already integrated components and
                    ready-to-go code.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-puzzle-piece fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Reusable apps</b> provide common
                    infrastructure, back-end functionality,
                    and user-facing components.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-tint fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Themes</b> provide default templates and
                    stylesheets for quick prototyping and easy customization.
                    {% endblocktrans %}
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <p class="lead text-center">
                {% blocktrans %}
                See <a href="http://pinaxproject.com/">pinaxproject.com</a>
                for more information.
                {% endblocktrans %}
            </p>
        </div>
    </section>
{% endblock %}

djangopinax/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load pinax_webanalytics_tags %}
{% load i18n %}


{% block styles %}
    <link href="{% static "css/site.css" %}" rel="stylesheet" />
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    <script src="{% static "js/site.js" %}"></script>
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}