djangopinax/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^account/social/accounts/$", TemplateView.as_view(template_name="account/social.html"), name="account_social_accounts"),
    url(r"^account/social/", include("social_django.urls", namespace="social")),
    url(r'^mods/', include('mods.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mods/urls.py
from django.conf.urls import url
from django.conf.urls import include

from . import views

app_name = 'mods'
urlpatterns = [
    url(r'^$', views.listcategories, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.PublicationView.as_view(), name='publicationview'),
    #url(r'^(?P<pk>[0-9]+)/$', views.Publication.as_view(), name='publicationview'),
    url(r'^(?P<publication_id>[0-9]+)/file/(?P<pk>[0-9]+)/$', views.FileView.as_view(), name='viewfile'),
    # url(r'^(?P<publication_id>[0-9]+)/file/(?P<file_id>[0-9]+)/download/$', views.GoToDownload, name='GoToDownload'),
    url(r'^file/(?P<file_id>[0-9]+)/$', views.downloader, name='goToDownload'),
    url(r'^(?P<publication_id>[0-9]+)/upload/$', views.upload, name='upload'),
    url(r'^(?P<publication_id>[0-9]+)/report/$', views.ReportView.as_view(), name='report'),

    url(r'^user/(?P<author>.+)/', views.UserPublications.as_view(), name='userpublications'),
    url(r'^modpublications/', views.ModPublications.as_view(), name='modpublications'),

    # zarzadzanie publikacjami:
    url(r'^(?P<pk>[0-9]+)/edit/$', views.PublicationEdit.as_view(), name='publicationedit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.PublicationDelete.as_view(), name='publicationdelete'),
    #url(r'^newpublication/', views.newPublication, name='newpublication'),
    url(r'^categoryview/(?P<category_slug>.+)/newpublication/', views.PublicationCreate.as_view(), name='newpublicationwithcategory'),
    url(r'^newpublication/', views.PublicationCreate.as_view(), name='newpublication'),

    url(r'^categoryview/(?P<category_slug>.+)/', views.categoryview, name='categoryview'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^user/(?P<author>.+)/', views.UserPublications.as_view(), name='userpublications'),
]

mods/forms.py
from django import forms
from .models import File, Image, Publication, Category, Report
from django.forms.models import inlineformset_factory
class FileForm(forms.ModelForm):
	class Meta:
		model = File
		fields = ['title', 'version', 'description', 'physicalfile',]

class ImgForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ['image',]

class PublicationForm(forms.ModelForm):
	class Meta:
		model = Publication
		fields = ['title', 'description', 'slug', 'category', 'video', ]

class ReportForm(forms.ModelForm):
	class Meta:
		model = Report
		fields = ['reason', 'comment', ]

fileformset = inlineformset_factory(Publication, File, form=FileForm, exclude=[],can_delete=True, extra=3, max_num=10)
imageformset = inlineformset_factory(Publication, Image, form=ImgForm, can_delete=True, exclude=[], extra=3, max_num=10)

mods/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from wsgiref.util import FileWrapper
from django.views import generic
from .models import File, Publication, Image, Category, Report
from django.http import HttpResponseRedirect, HttpResponse, StreamingHttpResponse
from .forms import FileForm, PublicationForm, ImgForm, fileformset, imageformset, ReportForm
import mimetypes, os, tempfile, zipfile
from django.http import Http404
from django.forms.formsets import formset_factory
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormView
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from os.path import basename
from datetime import datetime, date, time


# Create your views here.

class IndexView(generic.ListView):  # ten widok nie jest wykorzystywany, prawdopodobnie do przerobienia na widok publikacji nieopublikowanych dla moderatorow
    template_name = 'mods/index.html'
    context_object_name = 'publicationlist'

    def get_queryset(self):
        return Publication.objects.order_by('-pub_date')

class UserPublications(generic.ListView):
    template_name = 'mods/userpublications.html'
    context_object_name = 'userpublications'

    def get_queryset(self, **kwargs):
        return Publication.objects.filter(author__username=self.kwargs['author'], availability=True).order_by('-pub_date')

class ModPublications(generic.ListView):
    template_name = 'mods/modpublications.html'
    context_object_name = 'modpublications'
    success_url = reverse_lazy('mods:index')

    def post(self, request):
        accepted = request.POST.getlist('accepted')
        for pub in accepted:
            pubobject = get_object_or_404(Publication, pk=pub)
            pubobject.availability = True
            pubobject.save()
            for file in pubobject.get_files():
                file.availability = True
                file.save()
        return self.form_valid()

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Moderators').exists():
            return super(ModPublications, self).dispatch(request, *args, **kwargs)
        else:
            raise Http404()

    def form_valid(self):
        messages.success(self.request, 'Pomyślnie zaakceptowales publikacje!')
        return HttpResponseRedirect(self.success_url)

    def get_queryset(self, *args, **kwargs):
        return Publication.objects.filter(availability=False)


class PublicationView(generic.DetailView):
    template_name = 'mods/pubdetail.html'
    model = Publication

    def post(self, request, pk):
        view = multidownload(self.request)
        return view

    def get_object(self, queryset=None):
        obj = super(PublicationView, self).get_object(queryset)
        if obj.author is self.request.user or self.request.user.is_superuser:
            return obj
        if not obj.availability:
            raise Http404()
        else:
            return obj

    def filelist(self):
        return File.objects.filter(publicationfk=self.object, availability=1)

def multidownload(request):
    files = request.POST.getlist('multidownload')
    if len(files) is 1: #tylko 1 plik, przekierowac do gotodownlaod zeby nie zipowac
        fileobj = get_object_or_404(File, pk=files[0])
        return downloader(request, fileobj.id)
    temp = tempfile.NamedTemporaryFile()
    archive = zipfile.ZipFile(temp, 'w', zipfile.ZIP_DEFLATED)
    for file in files:
        fileobj = get_object_or_404(File, pk=file)
        file_full_path = "{}/{}".format(settings.MEDIA_ROOT, fileobj.physicalfile)
        archive.write(file_full_path, basename(file_full_path))
        fileobj.downloads += 1
        fileobj.save()
    archive.close()
    wrapper = FileWrapper(open(temp.name, 'rb'), 4096)
    response = HttpResponse(wrapper, content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=MultiDownload_{0}.zip'.format(datetime.now().strftime("%Y%m%d%H%M"))
    response['Content-Length'] = temp.tell()
    temp.seek(0)
    return response

class FileView(generic.DetailView):
    template_name = 'mods/detail.html'
    model = File

    def get_object(self, queryset=None):
        obj = super(FileView, self).get_object(queryset)
        if not obj.availability:
            raise Http404()
        else:
            return obj

class PublicationCreate(CreateView, LoginRequiredMixin):
    model = Publication
    form_class = PublicationForm
    template_name = 'mods/pubedit.html'
    login_url = '/login/'

    def get_success_url(self):
        self.success_url = reverse('mods:publicationview', args=(self.object.id,))
        return self.success_url

    def get_initial(self):
        initial = super(PublicationCreate, self).get_initial()
        if self.kwargs is not None and 'category_slug' in self.kwargs:
            initial['category'] = Category.objects.get(slug=self.kwargs['category_slug'])
        return initial

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        pubform = self.get_form(form_class)
        fileform = fileformset(instance=self.object)
        imgform = imageformset(instance=self.object)

        return self.render_to_response(
            self.get_context_data(pubform=pubform, fileform=fileform, imgform=imgform))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        pubform = self.get_form(form_class)
        fileform = fileformset(self.request.POST, self.request.FILES, instance=self.object)
        imgform = imageformset(self.request.POST, self.request.FILES, instance=self.object)

        if pubform.is_valid() and fileform.is_valid() and imgform.is_valid():
            return self.form_valid(pubform, fileform, imgform)
        else:
            return self.form_invalid(pubform, fileform, imgform)

    def form_valid(self, pubform, fileform, imgform):
        pubform.availability = True

        self.object = pubform.save(commit=False)
        self.object.author = self.request.user
        if self.request.user.is_superuser:
            self.object.availability = True
        self.object.save()

        fileform.instance = self.object
        files = fileform.save(commit=False)
        for file in files:
            file.author = self.request.user
            if self.request.user.is_superuser:
                file.availability = True
            file.save()

        imgform.instance = self.object
        imgform.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, pubform, fileform, imgform):
        return self.render_to_response(self.get_context_data(pubform=pubform,
                                                             fileform=fileform,
                                                             imgform=imgform))

class PublicationEdit(UpdateView, LoginRequiredMixin):
    model = Publication
    form_class = PublicationForm
    template_name = 'mods/pubedit.html'
    login_url = '/login/'

    def get_success_url(self):
        self.success_url = reverse('mods:publicationview', args=(self.object.id,))
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super(PublicationEdit, self).get_context_data(**kwargs)
        if self.request.POST:
            context['pubform'] = PublicationForm(self.request.POST, instance=self.object)
            context['fileform'] = fileformset(self.request.POST, self.request.FILES, instance=self.object)
            context['imgform'] = imageformset(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['pubform'] = PublicationForm(instance=self.object)
            context['fileform'] = fileformset(instance=self.object)
            context['imgform'] = imageformset(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        pubform = self.get_form(form_class)
        fileform = fileformset(self.request.POST, self.request.FILES, instance=self.object)
        imgform = imageformset(self.request.POST, self.request.FILES, instance=self.object)

        if pubform.is_valid() and fileform.is_valid() and imgform.is_valid():
            return self.form_valid(pubform, fileform, imgform)
        else:
            return self.form_invalid(pubform, fileform, imgform)

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author is self.request.user or self.request.user.is_superuser:
            return super(PublicationEdit, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('mods:publicationview', args=(obj.id,)))

    def form_valid(self, pubform, fileform, imgform):
        self.object = pubform.save()
        fileform.instance = self.object
        fileform.save()
        imgform.instance = self.object
        imgform.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, pubform, fileform, imgform):
        return self.render_to_response(self.get_context_data(pubform=pubform,
                                                             fileform=fileform,
                                                             imgform=imgform))


class PublicationDelete(DeleteView, LoginRequiredMixin):
    model = Publication
    form_class = PublicationForm
    template_name = 'mods/publicationdelete.html'
    login_url = '/login/'
    success_url = reverse_lazy('mods:categories')

mods/templates/mods/category.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}

{% with categories|first as first %}
Kategoria rodzic: <a href="{% url 'mods:category' first.slug %}">{{ first.title }}</a>
<br><br>

{% with categories|last as last %}
Kategoria: <a href="{% url 'mods:category' first.slug|add:'/'|add:last.slug %}">{{ last.title }}</a> <br>
Opis {{ last.description }} <br>
Obrazek: <img src="{{ last.image.url }}" height="500"><br><br>



{% with '/' as link %}
{% for i in categories %}
{% link|add:i.slug|add:'/' %}
{% endfor %}
{% include link %}
{% endwith %}


{{ link }}

{% endwith %}
{% endwith %}
{% endblock %}

mods/templates/mods/catview.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
{% if category.subcategoryof %}
<h1> Podategoria:{{ category.title }} </h1><br>
<h2> Rodzic: {{ category.subcategoryof }}</h2>
{% else %}
<h1> Kategoria: {{ category.title }} </h1><br>
{% endif %}

{% if subcategories %}
<h2>Dostępne podkategorie: </h2>
{% for subcat in subcategories %}
Podkategoria: <a href="{% url 'mods:categoryview' subcat.slug %}">{{ subcat.title }}</a> <br>
Opis {{ subcat.description }} <br>
Obrazek: <img src="{{ subcat.image.thumbnail.200x200 }}" /><br><hr><br>


{% endfor %}
{% endif %}

{% if publications %}
<h2> Dostępne publikacje: </h2>

{% for pub in publications %}
<a href="{{ pub.get_first_image.image.url }}"><img src="{{ pub.get_first_image.image.thumbnail.150x250 }}"/></a><br>
<li><a href="{% url 'mods:publicationview' pub.id %}"> {{ pub.title }} </a></li> <br>
Ilość pobrań: {{ pub.TotalDownloads }} <br>
Autor: <a href="{% url 'mods:userpublications' pub.author.username %}">{{ pub.author }} </a><br>
Opis: {{ pub.description | truncatewords:20 }}<br> <hr>
{% endfor %}
{% else %}
Brak publikacji w tej kategorii
{% endif %}

<a href ="{% url 'mods:newpublicationwithcategory' category.slug %}">Dodaj publikacje w tej kategorii</a>


{% endblock %}

mods/templates/mods/detail.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
{% load verbose_names %}

<h1> {% get_verbose_field_name file "title" %}: {{ file.title }} </h1>

<h3><a href="{% url 'mods:goToDownload' file.id %}">Pobierz plik {{ file.physicalfile }} </a> </h3>

<h3> {% get_verbose_field_name file "version" %}: {{ file.version }}</h3>

<h3> {% get_verbose_field_name file "downloads" %}: {{ file.downloads }}</h3>
<h3> {% get_verbose_field_name file "description" %} : {{ file.description }}</h3>
<h3> {% get_verbose_field_name file "author" %} : <a href="{% url 'mods:userpublications' file.author.username %}">{{ file.author }} </a><br></h3>

{% load static %}
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% load ratings %}
{% ratings object %}

<h3> {% get_verbose_field_name file "pub_date" %} : {{ file.pub_date }}</h3>
<h3> {% get_verbose_field_name file "mod_date" %} : {{ file.mod_date }}</h3>
{% endblock %}

mods/templates/mods/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'mods/style.css' %}" />

{% if publicationlist %}
	<ul>
	{% for publication in publicationlist %}
		<li><a href="{% url 'mods:publicationview' publication.id %}"> {{ publication.title }} </a></li>
	{% endfor %}
	</ul>
{% else %}
	<p> Brak dostepnych publikacji. </p>
{% endif %}
<a href="{% url 'mods:newpublication' %}"> Dodaj nowa publikacje</a>

mods/templates/mods/listcategories.html
{% extends "site_base.html" %}

{% load i18n %}
{% load publication_count %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">

            {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<h3>
<a href ="{% url 'mods:newpublication' %}">Dodaj nowa publikacje</a><br>
    {% if user.is_superuser %}
    <a href="{% url 'mods:modpublications' %} ">Panel moderatora (oczekuje {% notacceptedcount %} publikacji)</a><br>
    {% endif %}
</h3>

{% if categorylist %}
{% for cat in categorylist %}
Kategoria: <a href="{% url 'mods:categoryview' cat.slug %}">{{ cat.title }}</a> <br>
Opis: {{ cat.description }} <br>
Ilość publikacji: {{ cat.get_publication_count }} <br>
Ilość podkategorii: {{ cat.get_subcategories_count }} <br>
Ilość publikacji w podkategoriach: {{ cat.get_subpublications_count }} <br>
Ilość publikacji razem: {{ cat.get_sumofpublications_count }} <br>
<ul>
{% for sub in cat.get_subcats %}
<li>Podkategoria: <a href="{% url 'mods:categoryview' sub.slug %}">{{ sub.title }}</a> </li>
{% endfor %}
</ul>


Obrazek: <img src="{{ cat.image.thumbnail.200x200 }}"><br><br>
{% endfor %}
{% else %}
Brak kategoriów
{% endif %}
        </div>
{% endblock %}

mods/templates/mods/newpublication.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
{% load staticfiles %}
 <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ pubform.non_field_errors }}</p>
            <p>
                  {% for field in pubform %}
                        <label for="prependedInput">{{ field.label }}</label>
                        <div class="input">
                            {{ field }}
                            <span class="help-inline">
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            </span>
                        </div>
                {% endfor %}
            </p>

     <p>{{ imgform.non_field_errors }}</p>
            <p>
                  {% for field in imgform %}
                        <label for="prependedInput">{{ field.label }}</label>
                        <div class="input">
                            {{ field }}
                            <span class="help-inline">
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            </span>
                        </div>
                {% endfor %}
            </p>

                 <p>{{ fileform.non_field_errors }}</p>
             <div class="col-md-4">
        {{ form.as_p }}

        <table class="table">
            {{ formset.management_form }}

            {% for form in formset.forms %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                            <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                {% endif %}
                <tr class="formset_row">
                    {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'add',
        deleteText: 'remove',
    })
    $("#input").append("<div class='box'></div>");
</script>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

            <p><input type="submit" value="Wyslij" /></p>
        </form>

{% endblock %}
<script src="{% static 'dist/js/jquery.formset.js' %}"></script>

mods/templates/mods/pubdetail.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}

{% load verbose_names %}
{% load embed_video_tags %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if not publication.availability %}
<h1>Publikacja nie zaakceptowana - nie jest widoczna publicznie!</h1>
{% endif %}

<h1> {% get_verbose_field_name publication "title" %}: {{ publication.title }} </h1>
 <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
{% for file in view.filelist %}
    <h3>   <input type="checkbox" name="multidownload" id="{{file.id}}" value={{file.id}} />
  <a href="{% url 'mods:viewfile' publication.id file.id %}">Pobierz plik {{ file.title }} </a> </h3>
{% endfor %}


                 <p><input type="submit" value="Pobierz zaznaczone pliki" /></p>
        </form>
<h3><a href="{% url 'mods:report' publication.id %}">Zgłoś tą publikację</a></h3>

<h3> Ilość pobrań: {{ publication.TotalDownloads }} </h3>
<h3> {% get_verbose_field_name publication "description" %} : {{ publication.description }}</h3>
<h3> {% get_verbose_field_name publication "author" %} : <a href="{% url 'mods:userpublications' publication.author.username %}">{{ publication.author }} </a></h3>
<h3> {% get_verbose_field_name publication "pub_date" %} : {{ publication.pub_date }}</h3>
<h3> {% get_verbose_field_name publication "mod_date" %} : {{ publication.mod_date }}</h3>


{% load static %}
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% load ratings %}
{% ratings object %}

<h3>Obrazki:</h3>
{% for image in publication.get_images %}
<a href="{{ image.image.url }}"><img src="{{ image.image.thumbnail.150x250 }}"/></a><br>
{% endfor %}



Film: {% video publication.video 'small' %}<br>

{% if user.username == publication.author.username or user.is_superuser %}

<a href="{% url 'mods:publicationedit' publication.id %}">Edytuj</a> <br>
<a href="{% url 'mods:publicationdelete' publication.id %}">Usuń</a><br>
<a href="{% url 'mods:upload' publication.id %}">Dodaj nowy plik do wybranej publikacji (treba tu dodac warunek usera).</a>


{% else %}
{% endif %}
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
        var d = document, s = d.createElement('script');

        s.src = '//djangofilesharer.disqus.com/embed.js';  // IMPORTANT: Replace EXAMPLE with your forum shortname!

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock %}

mods/templates/mods/publication_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

mods/templates/mods/publicationreport.html
{% extends "site_base.html" %}
{% load staticfiles %}


{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
<div class="col-md-4">
    {% load staticfiles %}
<form  method="post" enctype="multipart/form-data">
            {% csrf_token %}

{{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
</div>
{% endblock %}

mods/templates/mods/upload.html
 <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>
                  {% for field in form %}
                        <label for="prependedInput">{{ field.label }}</label> 
                        <div class="input"> 
                            {{ field }}
                            <span class="help-inline">
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        {{ error|escape }}
                                    {% endfor %}
                                {% endif %}
                            </span>
                        </div> 
                    </div>   
                {% endfor %}
            </p>
            <p><input type="submit" value="Wyslij" /></p>
        </form>

mods/templates/mods/userpublications.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">

{% if userpublications %}
<h2> Dostępne publikacje użytkownika: </h2>

{% for pub in userpublications %}
<a href="{{ pub.get_first_image.image.url }}"><img src="{{ pub.get_first_image.image.thumbnail.150x250 }}"/></a><br>
<li><a href="{% url 'mods:publicationview' pub.id %}"> {{ pub.title }} </a></li> <br>
Ilość pobrań: {{ pub.TotalDownloads }} <br>
Autor: {{ pub.author }}<br>
Opis: {{ pub.description | truncatewords:20 }}<br>
            {% if user.username == userpublications.author.username or user.is_superuser %}
            <a href="{% url 'mods:publicationedit' pub.id %}">Edytuj</a> <br>
            <a href="{% url 'mods:publicationdelete' pub.id %}">Usuń</a><br>
            {% endif %}

            <hr>
{% endfor %}
{% else %}
Brak publikacji tego uzytkownika
{% endif %}
        </div>
        {% endblock %}